name: retrotrack
description: Retro Facial Temperature Tracking App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.5.8+2
  firebase_core: ^0.4.0
  firebase_core_web: ^0.1.1+2
  firebase_ml_vision: ^0.9.2+1
  flutter_image_compress: ^0.6.8
  flutter_hooks: ^0.10.0
  google_fonts: ^1.1.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  hooks_riverpod: ^0.1.0
  image: ^2.1.13
  image_picker: ^0.6.7+2
  path: ^1.7.0
  path_provider: ^1.6.11
  provider: ^4.1.3
  riverpod: ^0.1.0
  snappable: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

dependency_overrides:
  dartx: ">=0.2.0 <1.0.0"
  path: ">=1.6.0 <2.0.0"


flutter:
  uses-material-design: true
