name: retrotrack
description: Retro Facial Temperature Tracking App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.0
  firebase_core_web: ^0.1.1+2
  firebase_ml_vision: ^0.9.2+1
  image: ^2.1.13
  image_picker: ^0.6.7+2
  google_fonts: ^1.1.0

  # state management
  riverpod: ^0.1.0
  flutter_riverpod: ^0.1.0
  camera: ^0.5.8+2
  path_provider: ^1.6.11
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
